// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jifnypccczqihcpcfckp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZm55cGNjY3pxaWhjcGNmY2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTI1NTEsImV4cCI6MjA2NDgyODU1MX0.8-6ntolPDg6bsbkJNtqK4mB8XZXaXRI2CRVoRX16aZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});